name: housework_bot
on: [push]

  # schedule:
  #   - cron: '30 21 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install simplejson
          pip install pandas
          pip install dotenv
          pip install pytz
          pip install line-bot-sdk

      - name: env
        env:
          OWM_PLACE_ID: ${{ secrets.OWM_PLACE_ID }}
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}

      - name: Run script on push
        run: |
          python3 index.py
